[workspace]
members = ["crates/cognos", "rom"]
resolver = "3"

[workspace.package]
version = "0.2.1"
edition = "2024"
description = "Pretty build graphs for your pretty Nix builds"
rust-version = "1.92.0"
license = "EUPL-1.2"
homepage = "https://github.com/manic-systems/rom"

[workspace.dependencies]
cognos = { path = "./crates/cognos", version = "1.0.1" }     # cognos is versioned independently

pound = "0.1.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_repr = "0.1.20"
crossterm = "0.29.0"
ratatui-core = { version = "0.1.0", features = ["scrolling-regions"] }
indexmap = { version = "2.14.0", features = ["serde"] }
csv = "1.4.0"
jiff = { version = "0.2.37", default-features = false, features = ["std"] }
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
eyre = "0.6.12"
etcetera = "0.11.0"
tempfile = "3.27.0"
unicode-width = "0.2.2"
libc = "0.2.183"
nix-derivation = "0.6.1"
signal-hook = "0.3.18"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
